
version: '3'
services:
  proxy-service:
    build:
      context: .
      args:
        - GITLAB_ID=${GIT_USERNAME}
        - GITLAB_TOKEN=${GIT_ACCESS_TOKEN}
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
  redis:
    image: docker.io/bitnami/redis
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=redis
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
      - 4317:4317
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

